version: '3.8'

services:
  lab-bash:
    image: debian:stable-slim
    container_name: debian_lab
    tty: true
    stdin_open: true
    

  database:
    image: mysql:8.0
    container_name: mysql_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: gestion_commande
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql   # Conserve les données MySQL
    

 